# Security Config
security:
  jwt:
    token:
      secret-key: 53ccr37
      exprired-lenght: 3600000

# MySQL Connection
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boxofficespringboot?useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    
# Show SQL
  jpa:
    show-sql: true
    
#Swagger configuration    
springdoc:
    pathsToMatch: /api/tickets/v1/**
    swagger-ui:
      use-root-path: true